# If your site is in 'https', then make sure your base url isn't written using 'http' otherwise your sitemap would
# contain http (as opposeed to https) URLs. This would affect Google indexing of your URLs.
baseURL: "https://cloudjur.com/"
title: Cloudjur
copyright: ""
paginate: 15
theme: [PaperMod]

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true
enableGitInfo: true
mainsections: ["blogs"]
hasCJKLanguage: true

minify:
  disableXML: true
  # minifyOutput: true

# permalinks:
#   blogs: "/:title/"

defaultContentLanguage: en
# defaultContentLanguageInSubdir: true

languages:
  en:
    label: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    
    menu:
      main:
        - identifier: search
          name: 🔍 Search
          url: search
          weight: 1
        - identifier: home
          name: 🏠 Home
          url: /
          weight: 2
        - identifier: blogs
          name: 📚 Blogs
          url: blogs
          weight: 3
        - identifier: about
          name: 🙋🏻‍♂️ About Me
          url: about
          weight: 10
        - identifier: tags
          name: 🧩 Tags
          url: tags
          weight: 15
        - identifier: archives
          name: ⏱️ Archives
          url: archives/
          weight: 20
        - identifier: Wiki
          name: 🤝 Wiki
          url: https://wiki.cloudjur.com
          weight: 60

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: "Cloudjur"
  author: Jun Kin
  # author: ["Me", "You"] # multiple authors

  defaultTheme: auto
  disableThemeToggle: true
  ShowShareButtons: true
  ShowReadingTime: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  displayFullLangName: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideFooter: false
  ShowRssButtonInSectionTermList: true
  ShowAllPagesInArchive: true
  ShowPageNums: true
  ShowToc: true
  
  profileMode:
    enabled: true
    title: Jun Kin
    imageUrl: "https://raw.githubusercontent.com/googlefonts/noto-emoji/master/svg/emoji_u1f9d1_1f3fb_200d_1f4bb.svg"
    imageTitle: My image
    buttons:
      - name: Blogs
        url: /blogs/
      - name: About Me
        url: /about/

  # homeInfoParams:
  #   Title: "Cloudjur"
  #   Content: Hi! I'm Jun Kin, and welcome to my home *cloud*. Enjoy the content!
    
  socialIcons:
    - name: Discord
      url: "https://discordapp.com/users/386723201830354946"
    - name: X
      url: "https://x.com/chaijunkin"
    - name: Linkedin
      url: "https://www.linkedin.com/in/chaijunkin"
    - name: email
      url: "mailto:chaijunkin@gmail.com"
    - name: github
      url: "https://github.com/chaijunkin"
    - name: youtube
      url: "https://youtube.com/@chaijunkin_ch"
    - name: KoFi
      url: "https://ko-fi.com/junkin"
    - name: rss
      url: /index.xml

  editPost:
    URL: "https://github.com/chaijunkin/www/blob/master/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  assets:
    disableHLJS: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/safari-pinned-tab.svg"

  # analytics:
  #   plausible:
  #     domain: "cloudjur.com"
  #     url: "https://plausible.io/js/plausible.js"
  #   umami:
  #     Site: "your-site-id"
  #     URL: "https://umami.yourdomain.com"

  cover:
      hidden: false # hide everywhere but not in structured data
      hiddenInList: false # hide on list pages and home
      hiddenInSingle: false # hide on single page

  fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

  StartYear: 2024

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    codeFences: true
    guessSyntax: true
    tabWidth: 4
    style: monokai

privacy:
  vimeo:
    disabled: false
    simple: true

  x:
    disabled: false
    enableDNT: true
    simple: true

  instagram:
    disabled: false
    simple: true

  youtube:
    disabled: false
    privacyEnhanced: true

services:
  instagram:
    disableInlineCSS: true
  x:
    disableInlineCSS: true